name: Linting

on: pull_request

jobs:
  jest:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint:prettier:check
